### ISSUE TITLE
ＣＳＳ

### ISSUE THREAD

**Issue by enter3017sky** [enter3017sky/mentor-program-2nd-blog#16]
如何將CSS應用於HTML
將CSS應用於您通常會遇到的HTML文檔有三種不同的方法，其中一些方法比其他方法更有用。在這裡，我們將簡要回顧每一個。
#### 1.置入式CSS(Inline styles)：
- 使用 `style="..."` 附加在任一個需要的 __tag__ 中, 
```html
<body>
    <h1 style="color: blue;background-color: yellow;border: 1px solid black;">Hello World!</h1>
    <p style="color:red;">This is my first CSS example</p>
</body>

```
#### 第二種外部CSS(External stylesheet):
- `<link>`元素用在 HTML 文件中，告訴瀏覽器在哪可以找到用來將網頁樣式化的 CSS 檔。這是一個空白元素，不需要結束標籤。通常位在`<head>`元素裡，它應該使用三個屬性：
  - href：此屬性指定了 CSS 檔的路徑。
  - type：此屬性設定了要連結的檔案類型，其值應該設為 `text/css` 。
  - rel：此屬性表明了 HTML 頁面與它連結之檔案的關係。連結 CSS 時，其值應該設為`stylesheet`。
```html
<link rel="stylesheet" type="text/css" href="main.css" />
```
#### 第三種內部CSS(Internal stylesheet)：
```html
<!DOCTYPE html> 
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Web Page Title</title>
      <style>
        div{
          color: red;
        }
        p{
          coler:yello;
        }
        #first{
          color: red;
        }
        #second{
          background-color:yellow;
        }
        .row {
          background:green;
        }
      </style>
  </head>
    <body>
      <div>
        <h1>H1的標題</h1>
          <p id="first" class="row">第一個段落</p>
        <h2>H2的標題</h2>
          <p id="second">第二個段落</p>
      </div>
    </body>
</html>
```

  ## CSS 階層式樣式表
1. Selector + 規則：先選到你要改變的元素，再來套用規則。
優先順序：ID > Class > Tag

#### ID Selector `#`:整個網頁上的ID只能有一個。
```css
#div {
  color:red;
}
#first {
  color:yellow;
}

```
#### Class Selector `.`: 一次套用多個地方。
```css
.row {
  color:yellow;
}
```
#### Tag Selector:
```css
p {
  background:black;
}
```
### 多層 Selector 示範
```css
1<div>                          1. div: 底下所有的東西都會被選到
2  <p id='hello'>Hello</p>      2. div p: 底下所有的 p 都會被選到
3  <p class='p'>                3. div span: 底下所有的 span 都會被選到 => 4,9
4    <span>world</span>         4. div > span: 用箭頭的話，只有下一層的 span 會被選到 => 9
5  </p>                         5. .p: class 是 p 的會被選到 => 3~9
6  <p class='p'>                6. p.p: 元素是p,class是 p 才會被選到 => 3~8
7    yoyoyoyoyo                 7. span.p: 元素是span,class='p' 才會被選到 => 9
8  </p>                         8. p span: p底下的span => 4
9  <span class='p'>!!!</span>   9. .p span: class='p' 底下的 span => 4
 </div>                         10. #hello: 選到 id 是 hello 的元素 => 2
```
---

**Comment by enter3017sky** [comment]
Box Modal:把每一個元素想成是盒子

display:block,in-line,inline-block, none

### margin: 外框的邊距
 - margin-top
 - margin-right
 - margin-bottom
 - margin-left

### margin: 10px 20px 30px 40px ;
        上  右  下  左

### margin: 20px 40px; 上下、左右

### padding: 內邊距

### border: 邊框
```css
.box{
  background:red;
  margin:40px;
  padding:20px;
  border: 5px solid #0088dd;
  width:300px;
  height:300px;
  box-sizing: border-box;
}
```
![image](https://ppt.cc/fPDOdx@.png)

![image](https://ppt.cc/fU0TOx@.png)

---


行內元素沒辦法設定 mrgin, width height

```css
    #box {
      background:red;  //這個背景色不會顯示，除非套用在<p>裡面
      margin:50px;
    }
  <span id='box'>
    <p>
      comtent
    </p>
  </span>
```
