### ISSUE TITLE
[筆記][MTR01]Lesson 2-2 CSS 

### ISSUE THREAD

**Issue by enter3017sky** [enter3017sky/mentor-program-2nd-blog#17]
### 對使用者的回應

- `:hover`: 當使用者將滑鼠等指標移到一個元素上面時，這個擬元素會被套用。這個事件無法在觸控螢幕上面運作，因為螢幕無法辨認使用者的手指是否移到元素上面。
- `active`: 當按鈕或連結這點按時，這個擬元素就會被套用。改變元素的樣式或稍微移動元素的位置，就可以讓按鈕或連結感覺像是被按下了。
- `focus`: 聚焦。
  - > 實際用法有待實驗。
- `:first-child`: 假如有三個 __box__，能選取第一個。
- `:nth-child()`
  - 用處：假如有 3 個 __box__，設定`margin-left:20px`，但第一個 __box__ 的左側又不想有 __margin__，此時就可以用 `nth-child(n)` 選取第一個 __box__ 並把 __margin__ 消除掉。 __總之，常用於排版。__
  - _“我不要左側 margin 之 消除版”_

```css
.box {
  width:200px;
  height:200px;
  display:inline-block;
  background:red;
  margin-left: 20px; /* 每個盒子之間有 20px 間距 */
}
.box:first-child{  /* 假定有三個 box，:first-child 能選取第一個盒子。 */
  background: green;
}
.box:nth-child(1){ /* 選取第一個 box 並設 marfib-left: 0px; */
  margin-left: 0px;
}
          /* 更多 :nth-child(n) 用法 */
      .box:nth-child(2n){ /* 選 2 的倍數 */
        background: green;
      }
      .box:nth-child(2n+1){ /* 選 2n+1 */
        background: orange;
      }
<body>
  <div class='box'>box</div>
  <div class='box'>box</div>
  <div class='box'>box</div>
  <div class='box'>box</div>
  <div class='box'>box</div>
  <div class='box'>box</div>
</body>
```

> [Lesson 2-2 之 CSS __07:21秒__ box 之間的 margin 之 debug 時間](https://www.lidemy.com/courses/378582/lectures/5786329)（這段很有趣）

---

## Pseudo Element

> 可以選到「不存在的元素」
> 要選的話，一定要有 `content: ''`
> CSS Selector 不只是 Selector，還可以創造 content 出來。
1. ::before
    - 沒設定 __position__ 的話會出現在 __content__ 的最前面

2. ::after
    - 沒設定 __position__ 的話會出現在 __content__ 的最後面

---

## 第一個方法：透過增加 span

1. div 底下增加 `<span>123</span>`。
2. 寫一個 `.box span` 選擇器。
3. 設定 position : 在 `.box` 設定 `position: relative;`。
4. 設定 position : 在 `.box span` 設定 `position:absolute;`。
> 在這步驟底下，不加 `position: relative;` 的話，定位點會跑去遊覽器視窗的右下角。 _有Step4.沒Step3.的意思。_

```css
.box {
  width:200px;
  height:200px;
  background:red;
  display:inline-block;
  margin-left: 20px;
  position: relative; /* Step.3 設定定位點 */
}
 .box span {          /* Step.2 增加 .box span Selector */
  position:absolute;  /* Step.4 設定定位點 */
  bottom:0px;         /* content 的位置 */
  right:0px;          /* content 的位置 */
}
```

```html
<html>
  <body>
    <div class='box'>box</div>
                  <!-- Step.1 div 裡面增加 span  -->
    <div class='box'>box<span>123</span></div>
    <div class='box'>box<span>456</span></div>
  </body>
</html>

```

---

### 第二個方法：html的結構完全不用動，純CSS的解法。

> `::before` 、 `:nth-child(n)` 的搭配使用。

1. 使用`::before` -> 設定 `.box::before` -> 設定 `position: absolute;`。
2. 這個時候想要調整第二個 box 的 before 的話，設定 `.box:nth-child(n)::before`。

```css
...
.box::before {
  content: '123 '; /* 內容的文字 */
  position: absolute;
  right: 0px; /* content 的位置 */
  bottom: 0px; /* content 的位置 */
}
.box:nth-child(2)::before {
  content: '456';
}
```

```html
<html>
  <body>
    <div class='box'>box</div>
    <div class='box'>box</div>
    <div class='box'>box</div>
  </body>
</html>

```

### 第三個方法：attr() 更神奇的方法

> `::before` 、 `attr()` 的搭配使用。
- attr() 設定你取名的屬性，它會自己去抓這個屬性的內容，放到 content 裡面。
- 自己設定的屬性，在前面加 data，與原生的屬性做區別。

```css
...
.box::before {
  content: attr(data-index); /* 自己設定的屬性，在前面加 data，與原生的屬性做區別 */
  position: absolute;
  right: 0px;
  bottom: 0px;
}
...
<div class='box' data-index='123'>box</div>
<div class='box' data-index='456'>box</div>
...
```

### CSS Selector

> 排版很好用
1. div + ul
2. div ~ ul

#### 同一個階層的情況下

> 如以下 html 範例

```html
<body>
  <div class='first'>first</div>
  <div class='box'>box</div>
  <div class='box'>box</div>
  <div class='box'>box</div>
  <div class='box'>box</div>
  <div class='box'>box</div>
</body>
```

1. `.first + .box`：選取 `.first` 後面第一個 `.box` 的元素

```css
.first + .box{
  background: green;
  margin-left: 10px;
}
```

2. `.first ~ .box`：選取 `.first` 後面所有的 `.box`。

```css
.first ~ .box{
  background: green;
  margin-left: 10px;
}
```

3. `.box + .box`：選取第一個 __box__ 以外的所有 __box__。
    - 排版用。設定 box 之間的 margin，這個方法是第一個以外的 box 加上 margin。
    - _“我不要左側 margin 之 pass 版”_
    - [codepen 範例](https://codepen.io/pqehwvjl/pen/GXzRMx)

```css
.box + .box{
  background: green;
  margin-left: 10px;
}
```
